# Generated by Django 3.2.8 on 2021-10-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.CharField(blank=True, default='../static/images/unnamed.png', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='Profile_avatar_placeholder_large.png', null=True, upload_to='profile_pic'),
        ),
    ]
